#!/usr/bin/env bash

set -eux
set -o pipefail

readonly kernel_versions=("4.4.45")
readonly rkt_version="1.26.0"

if [[ ! -f "./rkt/rkt" ]] \
  || [[ ! "$(./rkt/rkt version | awk '/rkt Version/{print $3}')" == "${rkt_version}" ]]; then

  curl -LsS "https://github.com/coreos/rkt/releases/download/v${rkt_version}/rkt-v${rkt_version}.tar.gz" \
    -o rkt.tgz

  mkdir -p rkt
  tar -xvf rkt.tgz -C rkt --strip-components=1
fi

# Pre-fetch stage1 dependency due to rkt#2241
# https://github.com/coreos/rkt/issues/2241
sudo ./rkt/rkt image fetch --insecure-options=image "coreos.com/rkt/stage1-kvm:${rkt_version}"

for kernel_version in "${kernel_versions[@]}"; do
  rm -f ./rkt-uuid
  sudo ./rkt/rkt \
    run --interactive \
    --uuid-file-save=./rkt-uuid \
    --insecure-options=image,all-run \
    --dns=8.8.8.8 \
    --stage1-name="kinvolk.io/aci/rkt/stage1-kvm:${rkt_version},kernelversion=${kernel_version}" \
    --volume=ebpf,kind=host,source="$PWD" \
    docker://golang:1.8.3-alpine3.6 \
    --memory=128M \
    --mount=volume=ebpf,target=/go/src/github.com/supershabam/ebpf \
    --environment=GOPATH=/go \
    --exec=/bin/sh -- -c \
    'cd /go/src/github.com/supershabam/ebpf &&
      go test -v ./...'

  test_status=$(sudo ./rkt/rkt status "$(<rkt-uuid)" | awk '/app-/{split($0,a,"=")} END{print a[2]}')
  if [[ $test_status -ne 0 ]]; then
    exit "$test_status"
  fi
done